<?xml version="1.0"?>
<!DOCTYPE hibernate-mapping PUBLIC "-//Hibernate/Hibernate Mapping DTD 3.0//EN"
"http://www.hibernate.org/dtd/hibernate-mapping-3.0.dtd">
<!-- Generated Apr 20, 2018 11:51:50 AM by Hibernate Tools 3.4.0.CR1 -->
<hibernate-mapping>
    <class name="org.cgiar.ccafs.marlo.data.model.UrlSynthesisLog" table="url_synthesis_log" optimistic-lock="none">
        <id name="id" type="java.lang.Long">
            <column name="id" />
            <generator class="identity" />
        </id>
        <many-to-one name="reportSynthesis" class="org.cgiar.ccafs.marlo.data.model.ReportSynthesis" fetch="select">
            <column name="report_synthesis_id" />
        </many-to-one>
        <many-to-one name="phase" class="org.cgiar.ccafs.marlo.data.model.Phase" fetch="select">
            <column name="id_phase" />
        </many-to-one>
        <many-to-one name="liaisonInstitution" class="org.cgiar.ccafs.marlo.data.model.LiaisonInstitution" fetch="select">
            <column name="liaison_institution_id" />
        </many-to-one>
        <many-to-one name="crp" class="org.cgiar.ccafs.marlo.data.model.GlobalUnit" fetch="select">
            <column name="global_unit_id" />
        </many-to-one>
        <property name="synthesisSection" type="string">
           <column name="synthesis_section" sql-type="TEXT" />
        </property>
        <property name="errorText" type="string">
           <column name="error_text" sql-type="TEXT" />
        </property>
        <property name="exceptionText" type="string">
           <column name="exception_text" sql-type="TEXT" />
        </property>
    </class>
</hibernate-mapping>